development:
  adapter: postgresql
  encoding: unicode
  database: d4ao7t1jlm4ipu
  pool: 5
  timeout: 5000
  username: ocwpvnbboavdjh

test:
  adapter: postgresql
  encoding: unicode
  database: d4ao7t1jlm4ipu
  pool: 5
  timeout: 5000
  username: ocwpvnbboavdjh
